import type { AppreciationArchetype, ArchetypeId } from './archetypes';

export const archetypesDe: Record<ArchetypeId, AppreciationArchetype> = {
  'spotlight-seeker': {
    id: 'spotlight-seeker',
    name: 'Feuer',
    description: 'Gedeiht bei externer Bestätigung und sichtbarer Anerkennung vor anderen.',
    preferredRecognition: [
      'Shoutouts in Teambesprechungen',
      'Anerkennung in Unternehmensnewslettern oder Updates',
      'Social Media oder unternehmensweite Shoutouts',
      'Sichtbare Auszeichnungen oder Zertifikate',
    ],
    do: [
      'Erfolge in Teambesprechungen feiern',
      'Shoutouts geben, wo Kollegen und Führungskräfte sie sehen können',
      'Bei Bedarf Führungskräfte in Lob-E-Mails in CC setzen',
      'Sie in Unternehmens- oder Teamkommunikation hervorheben',
      'Sichtbare Auszeichnungen oder Zertifikate für ihre Beiträge erstellen',
    ],
    dont: [
      'Ihre Beiträge für das weitere Team völlig unsichtbar halten',
      'Sie nur in privaten Kanälen wertschätzen',
      'Annehmen, dass sie sich wertgeschätzt fühlen ohne sichtbare Anerkennung',
      'Anerkennung verzögern, bis die Wirkung verblasst ist',
    ],
    suggestedChannels: [
      'Teambesprechungen und All-Hands',
      'Unternehmensnewsletter oder interne Blogs',
      'Öffentliche Slack/Teams-Kanäle',
      'Auszeichnungszeremonien oder Anerkennungsrituale',
    ],
    suggestedPhrases: [
      'Ich möchte [Name] vor dem Team für die herausragende Arbeit an [Projekt] würdigen.',
      'Großer Shoutout an [Name] für das Über-sich-Hinauswachsen bei [Aufgabe] – das hatte enorme Auswirkungen auf [Ergebnis].',
      'Feiern wir alle [Name]s Erfolg in [Bereich]; ihr Einsatz hat das ganze Team wirklich gehoben.',
      'Ich hebe [Name] in unserem Update hervor, weil ihr Beitrag zu [Initiative] einen sichtbaren Unterschied gemacht hat.',
    ],
  },
  'quiet-achiever': {
    id: 'quiet-achiever',
    name: 'Mond',
    description: 'Schätzt echte, persönliche Verbindung und bevorzugt Anerkennung in privaten Räumen.',
    preferredRecognition: [
      '1:1-Gespräche',
      'Private, durchdachte Nachrichten',
      'Handgeschriebene oder persönliche Notizen',
      'Ruhige Anerkennung von Arbeit hinter den Kulissen',
    ],
    do: [
      'Dedizierte Wertschätzungszeit in 1:1s einplanen',
      'Private Notizen oder Nachrichten senden, die persönlich und aufrichtig wirken',
      'Ihre Arbeit hinter den Kulissen ausdrücklich anerkennen',
      'Sie direkt fragen, wie sie anerkannt werden möchten',
      'Ihre Präferenz für Privatsphäre bei der Anerkennung schützen',
    ],
    dont: [
      'Sie unerwartet in großen öffentlichen Foren hervorheben',
      'Sie mit großem öffentlichem Lob auf den Spot setzen',
      'Details ihrer Arbeit teilen, ohne ihr Wohlbefinden zu prüfen',
      'Annehmen, dass das, was andere motiviert, bei ihnen genauso funktioniert',
    ],
    suggestedChannels: [
      '1:1-Meetings',
      'Direktnachrichten (Chat-Tools)',
      'Private E-Mail',
      'Handgeschriebene oder physische Notizen',
    ],
    suggestedPhrases: [
      'Ich wollte mich persönlich für [spezifischen Beitrag] bedanken – er hat einen echten Unterschied für [Wirkung] gemacht.',
      'Ich habe wirklich geschätzt, wie du [Situation] gemeistert hast; dein Ansatz zeigte [Stärken oder Qualitäten].',
      'Dein Beitrag zu [Projekt] blieb nicht unbemerkt, auch wenn er hinter den Kulissen war. Er war wichtig, weil [Grund].',
      'Ich schätze die Art, wie du konsequent [Verhalten] zeigst; es hat eine ruhige aber kraftvolle Wirkung auf das Team.',
    ],
  },
  'word-collector': {
    id: 'word-collector',
    name: 'Wind',
    description: 'Schätzt durchdachte, gut formulierte Worte, die sie später lesen und reflektieren können.',
    preferredRecognition: [
      'Detaillierte E-Mails, die ihre Wirkung beschreiben',
      'Schriftliche Notizen mit konkreten Beispielen',
      'Dokumentations-Hervorhebungen oder schriftliche Shoutouts',
      'Nachrichten, die sie speichern und später erneut lesen können',
    ],
    do: [
      'Detaillierte Nachrichten mit konkreten Beispielen ihrer Wirkung schreiben',
      'Das „Warum" hinter deiner Wertschätzung erklären',
      'Ihre Beiträge schriftlich festhalten, damit sie später darauf zurückgreifen können',
      'Ihre einzigartigen Stärken und ihren Beitrag zum Team hervorheben',
    ],
    dont: [
      'Nur auf allgemeine Phrasen wie „gute Arbeit" oder „toll gemacht" vertrauen',
      'Die Details dessen, was sie taten und warum es wichtig war, weglassen',
      'Schriftliche Anerkennung ohne Nachdenken oder Sorgfalt überstürzen',
      'Annehmen, dass ein schnelles mündliches Danke allein ausreicht',
    ],
    suggestedChannels: [
      'E-Mail oder längere Nachrichten',
      'Leistungsnotizen oder Feedback-Dokumente',
      'Schriftliche Shoutouts in Dokumentation oder Teamseiten',
      'Dankeskarten oder schriftliche Notizen',
    ],
    suggestedPhrases: [
      'Ich wollte einen Moment nehmen, um aufzuschreiben, wie sehr ich deine Arbeit an [Projekt] schätze. Speziell als du [Beispiel], führte das zu [Wirkung].',
      'Dein durchdachter Ansatz bei [Situation] stach wirklich hervor, weil [Grund]; er zeigte [Stärken].',
      'Ich schreibe das, damit du einen Nachweis hast, wie wichtig dein Beitrag zu [Initiative] für [Team, Kunde oder Ergebnis] war.',
      'Was ich an deiner Arbeit am meisten schätze, ist [einzigartiger Beitrag]; sie hilft uns konsequent bei [Ergebnis].',
    ],
  },
  'reward-enthusiast': {
    id: 'reward-enthusiast',
    name: 'Wasser',
    description: 'Fühlt sich am meisten anerkannt, wenn Wertschätzung mit greifbaren Belohnungen oder Erlebnissen einhergeht.',
    preferredRecognition: [
      'Kleine Geschenke oder Gutscheine',
      'Erlebnisse (Teamessen, Events, Feiern)',
      'Physische Symbole wie Zertifikate oder Trophäen',
      'Zusätzliche Vergünstigungen wie flexible Arbeitszeiten oder bevorzugte Parkplätze',
    ],
    do: [
      'Mündliches oder schriftliches Lob mit kleinen, durchdachten Gesten verbinden',
      'Belohnungen wählen, die zu ihren persönlichen Interessen passen',
      'Erlebnisse (wie Essen oder Feiern) nutzen, um Erfolge zu markieren',
      'Sichtbare aber bedeutungsvolle Symbole der Wertschätzung schaffen',
    ],
    dont: [
      'Nur auf abstraktes Lob ohne Folgemaßnahmen vertrauen',
      'Annehmen, dass Einheitsbelohnungen bedeutungsvoll wirken',
      'Belohnungen nutzen, die nicht zu ihrem Geschmack oder Werten passen',
      'Belohnungen als Ersatz für aufrichtige Wertschätzung behandeln',
    ],
    suggestedChannels: [
      'Persönliche Feiern oder Übergaben',
      'Geschenkkarten oder digitale Gutscheine',
      'Unternehmens-Vergünstigungssysteme',
      'Team-Events oder gemeinsame Erlebnisse',
    ],
    suggestedPhrases: [
      'Ich möchte meine Wertschätzung mit [spezifischer Belohnung] zeigen, weil deine Arbeit an [Projekt] wirklich über sich hinausgewachsen ist.',
      'Deine harte Arbeit an [Initiative] verdient mehr als nur Worte, also haben wir [Erlebnis oder Vergünstigung] als Dankeschön arrangiert.',
      'Als Zeichen der Wertschätzung für deine Bemühungen bei [Aufgabe] wollten wir dir [Belohnung] anbieten, die zu deinen Interessen passt.',
      'Lass uns deinen Beitrag zu [Ergebnis] mit [Teamessen / kleines Geschenk / Erlebnis] feiern – du hast es dir wirklich verdient.',
    ],
  },
  'growth-chaser': {
    id: 'growth-chaser',
    name: 'Blitz',
    description: 'Wird durch Entwicklung, herausfordernde Möglichkeiten und klare Wachstumspfade motiviert.',
    preferredRecognition: [
      'Neue Verantwortlichkeiten oder Aufgabenbereich',
      'Sichtbare oder herausfordernde Projekte',
      'Mentoring und Sponsoring',
      'Schulungen, Kurse oder Lernbudgets',
    ],
    do: [
      'Deine Wertschätzung mit ihrem langfristigen Wachstum und Karriereweg verbinden',
      'Lernmöglichkeiten oder Schulungen als Teil der Anerkennung anbieten',
      'Sichtbare Projekte zuweisen, die zu ihren Stärken passen',
      'Nächste Schritte, Aufstieg und zukünftige Möglichkeiten besprechen',
      'Lob mit konkreten Entwicklungsmaßnahmen (Mentoring, Coaching, Projekte) verbinden',
    ],
    dont: [
      'Sie in denselben Aufgaben ohne Wachstum stagnieren lassen',
      'Nur mündliches Lob ohne vorausschauende Maßnahmen anbieten',
      'Ihre geäußerten Karriereziele oder -wünsche ignorieren',
      'Annehmen, dass sie zufrieden sind, ohne ihre Entwicklung zu prüfen',
    ],
    suggestedChannels: [
      'Karrierefokussierte 1:1-Gespräche',
      'Entwicklungspläne und Wachstums-Check-ins',
      'Mentoring- oder Sponsoring-Programme',
      'Lernplattformen und Schulungsbudgets',
    ],
    suggestedPhrases: [
      'Deine Arbeit an [Projekt] zeigte echtes Potenzial in [Fähigkeit/Bereich]; ich möchte gerne nächste Schritte mit dir erkunden.',
      'Angesichts dessen, was du bei [Initiative] erreicht hast, denke ich, du würdest bei [herausfordernde Aufgabe oder neue Verantwortung] glänzen.',
      'Ich schätze deine Wirkung auf [Ergebnis] und möchte diese Anerkennung mit [Kurs, Mentoring, neues Projekt] verbinden, um dein Wachstum zu unterstützen.',
      'Lass uns darüber sprechen, wie deine Beiträge zu [Bereich] in deinen nächsten Karriereschritt übersetzt werden können – dein Wachstum hat Priorität.',
    ],
  },
};
